# Generated by Django 4.0.3 on 2022-03-02 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(max_length=15)),
                ('book_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 2, 7, 41, 33, 468352, tzinfo=utc))),
            ],
            options={
                'unique_together': {('subscriber_id', 'book_id')},
            },
        ),
    ]
